### ISSUE TITLE
dotnet run doesn't work in /buisiness/MetadataDatabase

### ISSUE THREAD

**Issue by cquennouelle** [bat3/Health-Barbecue#42]
I met the following error when I run the command:

` $ dotnet run`
` 
Models\IModelContext.cs(1,7): error CS0246: Le nom de type ou d'espace de noms 'MongoDB' est introuvable (vous manque-t-il une directive using ou une référence d'assembly ?) [D:\Personnel\health-barbecue\Health-Barbecue\business\MetadataDatabase\MetadataDatabase.csproj]
Models\Series.cs(1,7): error CS0246: Le nom de type ou d'espace de noms 'MongoDB' est introuvable (vous manque-t-il une directive using ou une référence d'assembly ?) [D:\Personnel\health-barbecue\Health-Barbecue\business\MetadataDatabase\MetadataDatabase.csproj]
Models\Series.cs(2,7): error CS0246: Le nom de type ou d'espace de noms 'MongoDB' est introuvable (vous manque-t-il une directive using ou une référence d'assembly ?) [D:\Personnel\health-barbecue\Health-Barbecue\business\MetadataDatabase\MetadataDatabase.csproj]
Models\SeriesContext.cs(1,7): error CS0246: Le nom de type ou d'espace de noms 'MongoDB' est introuvable (vous manque-t-il une directive using ou une référence d'assembly ?) [D:\Personnel\health-barbecue\Health-Barbecue\business\MetadataDatabase\MetadataDatabase.csproj]
Repository\SeriesRepository.cs(5,7): error CS0246: Le nom de type ou d'espace de noms 'MongoDB' est introuvable (vous manque-t-il une directive using ou une référence d'assembly ?) [D:\Personnel\health-barbecue\Health-Barbecue\business\MetadataDatabase\MetadataDatabase.csproj]
Startup.cs(15,17): error CS0234: Le nom de type ou d'espace de noms 'OpenApi' n'existe pas dans l'espace de noms 'Microsoft' (vous manque-t-il une référence d'assembly ?) [D:\Personnel\health-barbecue\Health-Barbecue\business\MetadataDatabase\MetadataDatabase.csproj]
Models\IModelContext.cs(6,10): error CS0246: Le nom de type ou d'espace de noms 'IMongoCollection<>' est introuvable (vous manque-t-il une directive using ou une référence d'assembly ?) [D:\Personnel\health-barbecue\Health-Barbecue\business\MetadataDatabase\MetadataDatabase.csproj]
Models\SeriesContext.cs(9,10): error CS0246: Le nom de type ou d'espace de noms 'IMongoCollection<>' est introuvable (vous manque-t-il une directive using ou une référence d'assembly ?) [D:\Personnel\health-barbecue\Health-Barbecue\business\MetadataDatabase\MetadataDatabase.csproj]
Repository\SeriesRepository.cs(14,26): error CS0246: Le nom de type ou d'espace de noms 'IMongoCollection<>' est introuvable (vous manque-t-il une directive using ou une référence d'assembly ?) [D:\Personnel\health-barbecue\Health-Barbecue\business\MetadataDatabase\MetadataDatabase.csproj]
Models\SeriesContext.cs(8,26): error CS0246: Le nom de type ou d'espace de noms 'IMongoDatabase' est introuvable (vous manque-t-il une directive using ou une référence d'assembly ?) [D:\Personnel\health-barbecue\Health-Barbecue\business\MetadataDatabase\MetadataDatabase.csproj]
Models\Series.cs(8,10): error CS0246: Le nom de type ou d'espace de noms 'BsonIdAttribute' est introuvable (vous manque-t-il une directive using ou une référence d'assembly ?) [D:\Personnel\health-barbecue\Health-Barbecue\business\MetadataDatabase\MetadataDatabase.csproj]
Models\Series.cs(8,10): error CS0246: Le nom de type ou d'espace de noms 'BsonId' est introuvable (vous manque-t-il une directive using ou une référence d'assembly ?) [D:\Personnel\health-barbecue\Health-Barbecue\business\MetadataDatabase\MetadataDatabase.csproj]
Models\Series.cs(9,10): error CS0246: Le nom de type ou d'espace de noms 'BsonRepresentationAttribute' est introuvable (vous manque-t-il une directive using ou une référence d'assembly ?) [D:\Personnel\health-barbecue\Health-Barbecue\business\MetadataDatabase\MetadataDatabase.csproj]
Models\Series.cs(9,10): error CS0246: Le nom de type ou d'espace de noms 'BsonRepresentation' est introuvable (vous manque-t-il une directive using ou une rréférence d'assembly ?) [D:\Personnel\health-barbecue\Health-Barbecue\business\MetadataDatabase\MetadataDatabase.csproj]
Models\Series.cs(9,29): error CS0103: Le nom 'BsonType' n'existe pas dans le contexte actuel [D:\Personnel\health-barbecue\Health-Barbecue\business\MetadataDatabase\MetadataDatabase.csproj]

La build a échoué. Corrigez les erreurs de la build et réexécutez-la.
`

**Comment by cquennouelle** [comment]
With the following command:

`dotnet add MetadataDatabase.csproj package MongoDB.Driver -v 2.10.2`

The error is fixed:

`$ dotnet run`
`info: Microsoft.Hosting.Lifetime[0]
      Now listening on: https://localhost:5001
info: Microsoft.Hosting.Lifetime[0]
      Now listening on: http://localhost:5000
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Development
info: Microsoft.Hosting.Lifetime[0]
      Content root path: D:\Personnel\health-barbecue\Health-Barbecue\business\MetadataDatabase
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
System.NullReferenceException: Object reference not set to an instance of an object.
   at MetadataDatabase.Controllers.SeriesController.Post(SeriesDto series) in D:\Personnel\health-barbecue\Health-Barbecue\business\MetadataDatabase\Controllers\SeriesController.cs:line 44
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
info: Microsoft.Hosting.Lifetime[0]
      Application is shutting down...`
